spring:
  # 设置缓冲期，最大等待时间
  lifecycle:
    timeout-per-shutdown-phase: 5s
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# feign配置
feign:
  # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
  hystrix:
    enabled: false
  # 在feign中开启sentinel功能，默认情况下feign不开启hystrix功能
  sentinel:
    enable: true
  ## 配置httpclient线程池
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  # feign 开启Gzip压缩
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 60000
  #请求连接的超时时间
  ConnectTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

# 配置hystrix的参数
hystrix:
  threadpool:
    # default: 默认参数，作用的所有的hystrix的客户端,如果需要对某个具体的接口，可以写接口+方法名称
    default:
      coreSize: 500
  command:
    default:
      fallback:
        # 是否开启回退方法
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #缺省为1000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always

tml:
  swagger2:
    enabled: true
    description: ${info.description}
    title: ${info.name}
    version: ${info.version}
  tenant:
    tenantIdColumn: tenant_id
    ignoreTenantTables:
      - sys_tenant
      - sys_menu
      - sys_user_role
      - sys_role_menu
      - sys_role_enterprise
      - sys_dict_item
      - sys_api
      - oauth_client_details
      - oms_item
      - oms_item_kill
      - oms_item_kill_order
      - oms_random_code

  redisson:
    enable: true
  security:
    jwtEnable: true
    jwtSigningKey: jackson
    oauthPrefix: fast-cloud
    anonUris: #安全路径白名单
      - /actuator/**
      - /v2/api-docs
      - /v2/api-docs-ext
      - /swagger-resources/**
      - /doc.html
      - /webjars/**
      - /**/*.ico
      - /bootstrap/**
      - /css/**
      - /js/**
      - /images/**
      - /upload/**
      - /druid/**
      - /login
      - /admin/login
      - /admin/register
      - /admin/mobile/login/**
      - /auth/**
      - /welcome
      - /sys/user/findSecurityUserByUsername
      - /sys/user/findSecurityUserByPhone
      - /sys/user/findPermsByUserId
      - /sys/user/findRoleIdByUserId
      - /sys/user/findDataPermsByUserId
