spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        allow:
    dynamic:
      druid:
        filters: stat,wall
      p6spy: true # 默认false,建议线上关闭。
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/sb-security?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          druid:
            validation-query: select 'x'

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.tml.*.entity,com.tml.common.log
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag