spring:
  mail:
    protocol: smtp
    host: smtp.126.com
    port: 465
    username: xy_world_way@126.com
    password: abc123
    default-encoding: utf-8
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false