spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated #必须配置这个才会确认回调
    publisher-returns: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
        concurrency: 20 #同一个队列启动几个消费者
        max-concurrency: 30 #启动消费者最大数量
        prefetch: 1 #限制每次发送一条数据
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: false
          multiplier: 1.0 #时间策略乘数因子
          initial-interval: 1000ms
          max-interval: 1000ms
        default-requeue-rejected: true





